// Code generated by MockGen. DO NOT EDIT.
// Source: query/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/babylonchain/babylon/x/btccheckpoint/types"
	types0 "github.com/babylonchain/babylon/x/btclightclient/types"
	types1 "github.com/babylonchain/babylon/x/btcstaking/types"
	types2 "github.com/babylonchain/babylon/x/checkpointing/types"
	types3 "github.com/babylonchain/babylon/x/epoching/types"
	types4 "github.com/babylonchain/babylon/x/finality/types"
	types5 "github.com/babylonchain/babylon/x/monitor/types"
	types6 "github.com/babylonchain/babylon/x/zoneconcierge/types"
	chainhash "github.com/btcsuite/btcd/chaincfg/chainhash"
	coretypes "github.com/cometbft/cometbft/rpc/core/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	types7 "github.com/cosmos/cosmos-sdk/x/staking/types"
	gomock "github.com/golang/mock/gomock"
)

// MockBabylonQueryClient is a mock of BabylonQueryClient interface.
type MockBabylonQueryClient struct {
	ctrl     *gomock.Controller
	recorder *MockBabylonQueryClientMockRecorder
}

// MockBabylonQueryClientMockRecorder is the mock recorder for MockBabylonQueryClient.
type MockBabylonQueryClientMockRecorder struct {
	mock *MockBabylonQueryClient
}

// NewMockBabylonQueryClient creates a new mock instance.
func NewMockBabylonQueryClient(ctrl *gomock.Controller) *MockBabylonQueryClient {
	mock := &MockBabylonQueryClient{ctrl: ctrl}
	mock.recorder = &MockBabylonQueryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBabylonQueryClient) EXPECT() *MockBabylonQueryClientMockRecorder {
	return m.recorder
}

// ActiveBTCValidatorsAtHeight mocks base method.
func (m *MockBabylonQueryClient) ActiveBTCValidatorsAtHeight(height uint64, pagination *query.PageRequest) (*types1.QueryActiveBTCValidatorsAtHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveBTCValidatorsAtHeight", height, pagination)
	ret0, _ := ret[0].(*types1.QueryActiveBTCValidatorsAtHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveBTCValidatorsAtHeight indicates an expected call of ActiveBTCValidatorsAtHeight.
func (mr *MockBabylonQueryClientMockRecorder) ActiveBTCValidatorsAtHeight(height, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveBTCValidatorsAtHeight", reflect.TypeOf((*MockBabylonQueryClient)(nil).ActiveBTCValidatorsAtHeight), height, pagination)
}

// BTCBaseHeader mocks base method.
func (m *MockBabylonQueryClient) BTCBaseHeader() (*types0.QueryBaseHeaderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCBaseHeader")
	ret0, _ := ret[0].(*types0.QueryBaseHeaderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCBaseHeader indicates an expected call of BTCBaseHeader.
func (mr *MockBabylonQueryClientMockRecorder) BTCBaseHeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCBaseHeader", reflect.TypeOf((*MockBabylonQueryClient)(nil).BTCBaseHeader))
}

// BTCCheckpointInfo mocks base method.
func (m *MockBabylonQueryClient) BTCCheckpointInfo(epochNumber uint64) (*types.QueryBtcCheckpointInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCCheckpointInfo", epochNumber)
	ret0, _ := ret[0].(*types.QueryBtcCheckpointInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCCheckpointInfo indicates an expected call of BTCCheckpointInfo.
func (mr *MockBabylonQueryClientMockRecorder) BTCCheckpointInfo(epochNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCCheckpointInfo", reflect.TypeOf((*MockBabylonQueryClient)(nil).BTCCheckpointInfo), epochNumber)
}

// BTCCheckpointParams mocks base method.
func (m *MockBabylonQueryClient) BTCCheckpointParams() (*types.QueryParamsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCCheckpointParams")
	ret0, _ := ret[0].(*types.QueryParamsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCCheckpointParams indicates an expected call of BTCCheckpointParams.
func (mr *MockBabylonQueryClientMockRecorder) BTCCheckpointParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCCheckpointParams", reflect.TypeOf((*MockBabylonQueryClient)(nil).BTCCheckpointParams))
}

// BTCCheckpointsInfo mocks base method.
func (m *MockBabylonQueryClient) BTCCheckpointsInfo(pagination *query.PageRequest) (*types.QueryBtcCheckpointsInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCCheckpointsInfo", pagination)
	ret0, _ := ret[0].(*types.QueryBtcCheckpointsInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCCheckpointsInfo indicates an expected call of BTCCheckpointsInfo.
func (mr *MockBabylonQueryClientMockRecorder) BTCCheckpointsInfo(pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCCheckpointsInfo", reflect.TypeOf((*MockBabylonQueryClient)(nil).BTCCheckpointsInfo), pagination)
}

// BTCHeaderChainTip mocks base method.
func (m *MockBabylonQueryClient) BTCHeaderChainTip() (*types0.QueryTipResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCHeaderChainTip")
	ret0, _ := ret[0].(*types0.QueryTipResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCHeaderChainTip indicates an expected call of BTCHeaderChainTip.
func (mr *MockBabylonQueryClientMockRecorder) BTCHeaderChainTip() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCHeaderChainTip", reflect.TypeOf((*MockBabylonQueryClient)(nil).BTCHeaderChainTip))
}

// BTCMainChain mocks base method.
func (m *MockBabylonQueryClient) BTCMainChain(pagination *query.PageRequest) (*types0.QueryMainChainResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCMainChain", pagination)
	ret0, _ := ret[0].(*types0.QueryMainChainResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCMainChain indicates an expected call of BTCMainChain.
func (mr *MockBabylonQueryClientMockRecorder) BTCMainChain(pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCMainChain", reflect.TypeOf((*MockBabylonQueryClient)(nil).BTCMainChain), pagination)
}

// BTCValidatorDelegations mocks base method.
func (m *MockBabylonQueryClient) BTCValidatorDelegations(valBtcPkHex string, pagination *query.PageRequest) (*types1.QueryBTCValidatorDelegationsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCValidatorDelegations", valBtcPkHex, pagination)
	ret0, _ := ret[0].(*types1.QueryBTCValidatorDelegationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCValidatorDelegations indicates an expected call of BTCValidatorDelegations.
func (mr *MockBabylonQueryClientMockRecorder) BTCValidatorDelegations(valBtcPkHex, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCValidatorDelegations", reflect.TypeOf((*MockBabylonQueryClient)(nil).BTCValidatorDelegations), valBtcPkHex, pagination)
}

// BTCValidatorPowerAtHeight mocks base method.
func (m *MockBabylonQueryClient) BTCValidatorPowerAtHeight(valBtcPkHex string, height uint64) (*types1.QueryBTCValidatorPowerAtHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCValidatorPowerAtHeight", valBtcPkHex, height)
	ret0, _ := ret[0].(*types1.QueryBTCValidatorPowerAtHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCValidatorPowerAtHeight indicates an expected call of BTCValidatorPowerAtHeight.
func (mr *MockBabylonQueryClientMockRecorder) BTCValidatorPowerAtHeight(valBtcPkHex, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCValidatorPowerAtHeight", reflect.TypeOf((*MockBabylonQueryClient)(nil).BTCValidatorPowerAtHeight), valBtcPkHex, height)
}

// BTCValidators mocks base method.
func (m *MockBabylonQueryClient) BTCValidators(pagination *query.PageRequest) (*types1.QueryBTCValidatorsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BTCValidators", pagination)
	ret0, _ := ret[0].(*types1.QueryBTCValidatorsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BTCValidators indicates an expected call of BTCValidators.
func (mr *MockBabylonQueryClientMockRecorder) BTCValidators(pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BTCValidators", reflect.TypeOf((*MockBabylonQueryClient)(nil).BTCValidators), pagination)
}

// BlsPublicKeyList mocks base method.
func (m *MockBabylonQueryClient) BlsPublicKeyList(epochNumber uint64, pagination *query.PageRequest) (*types2.QueryBlsPublicKeyListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlsPublicKeyList", epochNumber, pagination)
	ret0, _ := ret[0].(*types2.QueryBlsPublicKeyListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlsPublicKeyList indicates an expected call of BlsPublicKeyList.
func (mr *MockBabylonQueryClientMockRecorder) BlsPublicKeyList(epochNumber, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlsPublicKeyList", reflect.TypeOf((*MockBabylonQueryClient)(nil).BlsPublicKeyList), epochNumber, pagination)
}

// ConnectedChainHeaders mocks base method.
func (m *MockBabylonQueryClient) ConnectedChainHeaders(chainID string, pagination *query.PageRequest) (*types6.QueryListHeadersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectedChainHeaders", chainID, pagination)
	ret0, _ := ret[0].(*types6.QueryListHeadersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectedChainHeaders indicates an expected call of ConnectedChainHeaders.
func (mr *MockBabylonQueryClientMockRecorder) ConnectedChainHeaders(chainID, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectedChainHeaders", reflect.TypeOf((*MockBabylonQueryClient)(nil).ConnectedChainHeaders), chainID, pagination)
}

// ConnectedChainList mocks base method.
func (m *MockBabylonQueryClient) ConnectedChainList() (*types6.QueryChainListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectedChainList")
	ret0, _ := ret[0].(*types6.QueryChainListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectedChainList indicates an expected call of ConnectedChainList.
func (mr *MockBabylonQueryClientMockRecorder) ConnectedChainList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectedChainList", reflect.TypeOf((*MockBabylonQueryClient)(nil).ConnectedChainList))
}

// ConnectedChainsEpochInfo mocks base method.
func (m *MockBabylonQueryClient) ConnectedChainsEpochInfo(chainIds []string, epochNum uint64) (*types6.QueryEpochChainsInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectedChainsEpochInfo", chainIds, epochNum)
	ret0, _ := ret[0].(*types6.QueryEpochChainsInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectedChainsEpochInfo indicates an expected call of ConnectedChainsEpochInfo.
func (mr *MockBabylonQueryClientMockRecorder) ConnectedChainsEpochInfo(chainIds, epochNum interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectedChainsEpochInfo", reflect.TypeOf((*MockBabylonQueryClient)(nil).ConnectedChainsEpochInfo), chainIds, epochNum)
}

// ConnectedChainsInfo mocks base method.
func (m *MockBabylonQueryClient) ConnectedChainsInfo(chainIds []string) (*types6.QueryChainsInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectedChainsInfo", chainIds)
	ret0, _ := ret[0].(*types6.QueryChainsInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectedChainsInfo indicates an expected call of ConnectedChainsInfo.
func (mr *MockBabylonQueryClientMockRecorder) ConnectedChainsInfo(chainIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectedChainsInfo", reflect.TypeOf((*MockBabylonQueryClient)(nil).ConnectedChainsInfo), chainIds)
}

// ContainsBTCBlock mocks base method.
func (m *MockBabylonQueryClient) ContainsBTCBlock(blockHash *chainhash.Hash) (*types0.QueryContainsBytesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContainsBTCBlock", blockHash)
	ret0, _ := ret[0].(*types0.QueryContainsBytesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ContainsBTCBlock indicates an expected call of ContainsBTCBlock.
func (mr *MockBabylonQueryClientMockRecorder) ContainsBTCBlock(blockHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContainsBTCBlock", reflect.TypeOf((*MockBabylonQueryClient)(nil).ContainsBTCBlock), blockHash)
}

// CurrentEpoch mocks base method.
func (m *MockBabylonQueryClient) CurrentEpoch() (*types3.QueryCurrentEpochResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentEpoch")
	ret0, _ := ret[0].(*types3.QueryCurrentEpochResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentEpoch indicates an expected call of CurrentEpoch.
func (mr *MockBabylonQueryClientMockRecorder) CurrentEpoch() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentEpoch", reflect.TypeOf((*MockBabylonQueryClient)(nil).CurrentEpoch))
}

// DelegationLifecycle mocks base method.
func (m *MockBabylonQueryClient) DelegationLifecycle(delegator string) (*types3.QueryDelegationLifecycleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelegationLifecycle", delegator)
	ret0, _ := ret[0].(*types3.QueryDelegationLifecycleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DelegationLifecycle indicates an expected call of DelegationLifecycle.
func (mr *MockBabylonQueryClientMockRecorder) DelegationLifecycle(delegator interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelegationLifecycle", reflect.TypeOf((*MockBabylonQueryClient)(nil).DelegationLifecycle), delegator)
}

// EndedEpochBTCHeight mocks base method.
func (m *MockBabylonQueryClient) EndedEpochBTCHeight(epochNum uint64) (*types5.QueryEndedEpochBtcHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndedEpochBTCHeight", epochNum)
	ret0, _ := ret[0].(*types5.QueryEndedEpochBtcHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EndedEpochBTCHeight indicates an expected call of EndedEpochBTCHeight.
func (mr *MockBabylonQueryClientMockRecorder) EndedEpochBTCHeight(epochNum interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndedEpochBTCHeight", reflect.TypeOf((*MockBabylonQueryClient)(nil).EndedEpochBTCHeight), epochNum)
}

// EpochStatusCount mocks base method.
func (m *MockBabylonQueryClient) EpochStatusCount(epochCount uint64) (*types2.QueryRecentEpochStatusCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EpochStatusCount", epochCount)
	ret0, _ := ret[0].(*types2.QueryRecentEpochStatusCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EpochStatusCount indicates an expected call of EpochStatusCount.
func (mr *MockBabylonQueryClientMockRecorder) EpochStatusCount(epochCount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EpochStatusCount", reflect.TypeOf((*MockBabylonQueryClient)(nil).EpochStatusCount), epochCount)
}

// EpochingParams mocks base method.
func (m *MockBabylonQueryClient) EpochingParams() (*types3.QueryParamsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EpochingParams")
	ret0, _ := ret[0].(*types3.QueryParamsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EpochingParams indicates an expected call of EpochingParams.
func (mr *MockBabylonQueryClientMockRecorder) EpochingParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EpochingParams", reflect.TypeOf((*MockBabylonQueryClient)(nil).EpochingParams))
}

// EpochsInfo mocks base method.
func (m *MockBabylonQueryClient) EpochsInfo(pagination *query.PageRequest) (*types3.QueryEpochsInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EpochsInfo", pagination)
	ret0, _ := ret[0].(*types3.QueryEpochsInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EpochsInfo indicates an expected call of EpochsInfo.
func (mr *MockBabylonQueryClientMockRecorder) EpochsInfo(pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EpochsInfo", reflect.TypeOf((*MockBabylonQueryClient)(nil).EpochsInfo), pagination)
}

// FinalizedConnectedChainsInfo mocks base method.
func (m *MockBabylonQueryClient) FinalizedConnectedChainsInfo(chainIds []string) (*types6.QueryFinalizedChainsInfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinalizedConnectedChainsInfo", chainIds)
	ret0, _ := ret[0].(*types6.QueryFinalizedChainsInfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinalizedConnectedChainsInfo indicates an expected call of FinalizedConnectedChainsInfo.
func (mr *MockBabylonQueryClientMockRecorder) FinalizedConnectedChainsInfo(chainIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinalizedConnectedChainsInfo", reflect.TypeOf((*MockBabylonQueryClient)(nil).FinalizedConnectedChainsInfo), chainIds)
}

// GetBlock mocks base method.
func (m *MockBabylonQueryClient) GetBlock(height int64) (*coretypes.ResultBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlock", height)
	ret0, _ := ret[0].(*coretypes.ResultBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlock indicates an expected call of GetBlock.
func (mr *MockBabylonQueryClientMockRecorder) GetBlock(height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlock", reflect.TypeOf((*MockBabylonQueryClient)(nil).GetBlock), height)
}

// GetTx mocks base method.
func (m *MockBabylonQueryClient) GetTx(hash []byte) (*coretypes.ResultTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTx", hash)
	ret0, _ := ret[0].(*coretypes.ResultTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTx indicates an expected call of GetTx.
func (mr *MockBabylonQueryClientMockRecorder) GetTx(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTx", reflect.TypeOf((*MockBabylonQueryClient)(nil).GetTx), hash)
}

// LatestEpochFromStatus mocks base method.
func (m *MockBabylonQueryClient) LatestEpochFromStatus(status types2.CheckpointStatus) (*types2.QueryLastCheckpointWithStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestEpochFromStatus", status)
	ret0, _ := ret[0].(*types2.QueryLastCheckpointWithStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestEpochFromStatus indicates an expected call of LatestEpochFromStatus.
func (mr *MockBabylonQueryClientMockRecorder) LatestEpochFromStatus(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestEpochFromStatus", reflect.TypeOf((*MockBabylonQueryClient)(nil).LatestEpochFromStatus), status)
}

// LatestEpochMsgs mocks base method.
func (m *MockBabylonQueryClient) LatestEpochMsgs(endEpoch, epochCount uint64, pagination *query.PageRequest) (*types3.QueryLatestEpochMsgsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestEpochMsgs", endEpoch, epochCount, pagination)
	ret0, _ := ret[0].(*types3.QueryLatestEpochMsgsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestEpochMsgs indicates an expected call of LatestEpochMsgs.
func (mr *MockBabylonQueryClientMockRecorder) LatestEpochMsgs(endEpoch, epochCount, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestEpochMsgs", reflect.TypeOf((*MockBabylonQueryClient)(nil).LatestEpochMsgs), endEpoch, epochCount, pagination)
}

// ListBlocks mocks base method.
func (m *MockBabylonQueryClient) ListBlocks(status types4.QueriedBlockStatus, pagination *query.PageRequest) (*types4.QueryListBlocksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlocks", status, pagination)
	ret0, _ := ret[0].(*types4.QueryListBlocksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlocks indicates an expected call of ListBlocks.
func (mr *MockBabylonQueryClientMockRecorder) ListBlocks(status, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlocks", reflect.TypeOf((*MockBabylonQueryClient)(nil).ListBlocks), status, pagination)
}

// QueryBTCCheckpoint mocks base method.
func (m *MockBabylonQueryClient) QueryBTCCheckpoint(f func(context.Context, types.QueryClient) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryBTCCheckpoint", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryBTCCheckpoint indicates an expected call of QueryBTCCheckpoint.
func (mr *MockBabylonQueryClientMockRecorder) QueryBTCCheckpoint(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryBTCCheckpoint", reflect.TypeOf((*MockBabylonQueryClient)(nil).QueryBTCCheckpoint), f)
}

// QueryBTCLightclient mocks base method.
func (m *MockBabylonQueryClient) QueryBTCLightclient(f func(context.Context, types0.QueryClient) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryBTCLightclient", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryBTCLightclient indicates an expected call of QueryBTCLightclient.
func (mr *MockBabylonQueryClientMockRecorder) QueryBTCLightclient(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryBTCLightclient", reflect.TypeOf((*MockBabylonQueryClient)(nil).QueryBTCLightclient), f)
}

// QueryBTCStaking mocks base method.
func (m *MockBabylonQueryClient) QueryBTCStaking(f func(context.Context, types1.QueryClient) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryBTCStaking", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryBTCStaking indicates an expected call of QueryBTCStaking.
func (mr *MockBabylonQueryClientMockRecorder) QueryBTCStaking(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryBTCStaking", reflect.TypeOf((*MockBabylonQueryClient)(nil).QueryBTCStaking), f)
}

// QueryCheckpointing mocks base method.
func (m *MockBabylonQueryClient) QueryCheckpointing(f func(context.Context, types2.QueryClient) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryCheckpointing", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryCheckpointing indicates an expected call of QueryCheckpointing.
func (mr *MockBabylonQueryClientMockRecorder) QueryCheckpointing(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCheckpointing", reflect.TypeOf((*MockBabylonQueryClient)(nil).QueryCheckpointing), f)
}

// QueryEpoching mocks base method.
func (m *MockBabylonQueryClient) QueryEpoching(f func(context.Context, types3.QueryClient) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryEpoching", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryEpoching indicates an expected call of QueryEpoching.
func (mr *MockBabylonQueryClientMockRecorder) QueryEpoching(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryEpoching", reflect.TypeOf((*MockBabylonQueryClient)(nil).QueryEpoching), f)
}

// QueryFinality mocks base method.
func (m *MockBabylonQueryClient) QueryFinality(f func(context.Context, types4.QueryClient) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryFinality", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryFinality indicates an expected call of QueryFinality.
func (mr *MockBabylonQueryClientMockRecorder) QueryFinality(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryFinality", reflect.TypeOf((*MockBabylonQueryClient)(nil).QueryFinality), f)
}

// QueryMonitor mocks base method.
func (m *MockBabylonQueryClient) QueryMonitor(f func(context.Context, types5.QueryClient) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryMonitor", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryMonitor indicates an expected call of QueryMonitor.
func (mr *MockBabylonQueryClientMockRecorder) QueryMonitor(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryMonitor", reflect.TypeOf((*MockBabylonQueryClient)(nil).QueryMonitor), f)
}

// QueryStaking mocks base method.
func (m *MockBabylonQueryClient) QueryStaking(f func(context.Context, types7.QueryClient) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryStaking", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryStaking indicates an expected call of QueryStaking.
func (mr *MockBabylonQueryClientMockRecorder) QueryStaking(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryStaking", reflect.TypeOf((*MockBabylonQueryClient)(nil).QueryStaking), f)
}

// QueryZoneConcierge mocks base method.
func (m *MockBabylonQueryClient) QueryZoneConcierge(f func(context.Context, types6.QueryClient) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryZoneConcierge", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryZoneConcierge indicates an expected call of QueryZoneConcierge.
func (mr *MockBabylonQueryClientMockRecorder) QueryZoneConcierge(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryZoneConcierge", reflect.TypeOf((*MockBabylonQueryClient)(nil).QueryZoneConcierge), f)
}

// RawCheckpoint mocks base method.
func (m *MockBabylonQueryClient) RawCheckpoint(epochNumber uint64) (*types2.QueryRawCheckpointResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawCheckpoint", epochNumber)
	ret0, _ := ret[0].(*types2.QueryRawCheckpointResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawCheckpoint indicates an expected call of RawCheckpoint.
func (mr *MockBabylonQueryClientMockRecorder) RawCheckpoint(epochNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawCheckpoint", reflect.TypeOf((*MockBabylonQueryClient)(nil).RawCheckpoint), epochNumber)
}

// RawCheckpointList mocks base method.
func (m *MockBabylonQueryClient) RawCheckpointList(status types2.CheckpointStatus, pagination *query.PageRequest) (*types2.QueryRawCheckpointListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawCheckpointList", status, pagination)
	ret0, _ := ret[0].(*types2.QueryRawCheckpointListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawCheckpointList indicates an expected call of RawCheckpointList.
func (mr *MockBabylonQueryClientMockRecorder) RawCheckpointList(status, pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawCheckpointList", reflect.TypeOf((*MockBabylonQueryClient)(nil).RawCheckpointList), status, pagination)
}

// RawCheckpoints mocks base method.
func (m *MockBabylonQueryClient) RawCheckpoints(pagination *query.PageRequest) (*types2.QueryRawCheckpointsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawCheckpoints", pagination)
	ret0, _ := ret[0].(*types2.QueryRawCheckpointsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawCheckpoints indicates an expected call of RawCheckpoints.
func (mr *MockBabylonQueryClientMockRecorder) RawCheckpoints(pagination interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawCheckpoints", reflect.TypeOf((*MockBabylonQueryClient)(nil).RawCheckpoints), pagination)
}

// ReportedCheckpointBTCHeight mocks base method.
func (m *MockBabylonQueryClient) ReportedCheckpointBTCHeight(hashStr string) (*types5.QueryReportedCheckpointBtcHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReportedCheckpointBTCHeight", hashStr)
	ret0, _ := ret[0].(*types5.QueryReportedCheckpointBtcHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReportedCheckpointBTCHeight indicates an expected call of ReportedCheckpointBTCHeight.
func (mr *MockBabylonQueryClientMockRecorder) ReportedCheckpointBTCHeight(hashStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReportedCheckpointBTCHeight", reflect.TypeOf((*MockBabylonQueryClient)(nil).ReportedCheckpointBTCHeight), hashStr)
}

// StakingParams mocks base method.
func (m *MockBabylonQueryClient) StakingParams() (*types7.QueryParamsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StakingParams")
	ret0, _ := ret[0].(*types7.QueryParamsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StakingParams indicates an expected call of StakingParams.
func (mr *MockBabylonQueryClientMockRecorder) StakingParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StakingParams", reflect.TypeOf((*MockBabylonQueryClient)(nil).StakingParams))
}

// Stop mocks base method.
func (m *MockBabylonQueryClient) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockBabylonQueryClientMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockBabylonQueryClient)(nil).Stop))
}

// Subscribe mocks base method.
func (m *MockBabylonQueryClient) Subscribe(subscriber, query string, outCapacity ...int) (<-chan coretypes.ResultEvent, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subscriber, query}
	for _, a := range outCapacity {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Subscribe", varargs...)
	ret0, _ := ret[0].(<-chan coretypes.ResultEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockBabylonQueryClientMockRecorder) Subscribe(subscriber, query interface{}, outCapacity ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subscriber, query}, outCapacity...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockBabylonQueryClient)(nil).Subscribe), varargs...)
}

// TxSearch mocks base method.
func (m *MockBabylonQueryClient) TxSearch(events []string, prove bool, page, perPage *int, orderBy string) (*coretypes.ResultTxSearch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxSearch", events, prove, page, perPage, orderBy)
	ret0, _ := ret[0].(*coretypes.ResultTxSearch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TxSearch indicates an expected call of TxSearch.
func (mr *MockBabylonQueryClientMockRecorder) TxSearch(events, prove, page, perPage, orderBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxSearch", reflect.TypeOf((*MockBabylonQueryClient)(nil).TxSearch), events, prove, page, perPage, orderBy)
}

// Unsubscribe mocks base method.
func (m *MockBabylonQueryClient) Unsubscribe(subscriber, query string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", subscriber, query)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockBabylonQueryClientMockRecorder) Unsubscribe(subscriber, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockBabylonQueryClient)(nil).Unsubscribe), subscriber, query)
}

// UnsubscribeAll mocks base method.
func (m *MockBabylonQueryClient) UnsubscribeAll(subscriber string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribeAll", subscriber)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnsubscribeAll indicates an expected call of UnsubscribeAll.
func (mr *MockBabylonQueryClientMockRecorder) UnsubscribeAll(subscriber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribeAll", reflect.TypeOf((*MockBabylonQueryClient)(nil).UnsubscribeAll), subscriber)
}

// VotesAtHeight mocks base method.
func (m *MockBabylonQueryClient) VotesAtHeight(height uint64) (*types4.QueryVotesAtHeightResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VotesAtHeight", height)
	ret0, _ := ret[0].(*types4.QueryVotesAtHeightResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VotesAtHeight indicates an expected call of VotesAtHeight.
func (mr *MockBabylonQueryClientMockRecorder) VotesAtHeight(height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VotesAtHeight", reflect.TypeOf((*MockBabylonQueryClient)(nil).VotesAtHeight), height)
}
